# Receive the release note by dependabot
version: 2

updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: "master"
    versioning-strategy: "increase"
